/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author je110
 */
public class FrmMenú extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenú.class.getName());
    private DesktopConFondo escritorioConFondo;
    /**
     * Creates new form FrmMenú
     */
    public FrmMenú() {
        initComponents();
        ImageIcon iconoFondo = new ImageIcon(getClass().getResource("/Icons/IconsProyecto2/FondoDesktopPane.png"));
        escritorioConFondo = new DesktopConFondo(iconoFondo);
        
        setContentPane(escritorioConFondo);
        escritorioConFondo.setLayout(null);
    }
    
    public void abrirInternal(javax.swing.JInternalFrame frame) {
        for (javax.swing.JInternalFrame f : escritorioConFondo.getAllFrames()) {
            if (f.getClass().equals(frame.getClass())) {
                try {
                    f.setIcon(false);
                    f.setSelected(true);
                    f.toFront();
                } catch (Exception ignored) {}
                return;
            }
        }
        escritorioConFondo.add(frame);
        frame.setVisible(true);
        try { frame.setSelected(true); } catch (Exception ignored) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        BarraMenu = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        GestorClientes = new javax.swing.JMenuItem();
        GestorVehiculos = new javax.swing.JMenuItem();
        GestorEmpleados = new javax.swing.JMenuItem();
        GestorReservas = new javax.swing.JMenuItem();
        GestorAlquileres = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        MenuOpciones.setText("Gestiones del Sistema de Control y Alquiler de Vehiculos");
        MenuOpciones.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        GestorClientes.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        GestorClientes.setText("Gestor de Clientes");
        GestorClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestorClientesActionPerformed(evt);
            }
        });
        MenuOpciones.add(GestorClientes);

        GestorVehiculos.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        GestorVehiculos.setText("Gestor de Vehiculos");
        GestorVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestorVehiculosActionPerformed(evt);
            }
        });
        MenuOpciones.add(GestorVehiculos);

        GestorEmpleados.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        GestorEmpleados.setText("Gestor de Empleados");
        GestorEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestorEmpleadosActionPerformed(evt);
            }
        });
        MenuOpciones.add(GestorEmpleados);

        GestorReservas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        GestorReservas.setText("Gestor de Reservas");
        MenuOpciones.add(GestorReservas);

        GestorAlquileres.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        GestorAlquileres.setText("Gestor de Alquileres");
        GestorAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestorAlquileresActionPerformed(evt);
            }
        });
        MenuOpciones.add(GestorAlquileres);

        BarraMenu.add(MenuOpciones);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestorClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestorClientesActionPerformed
        abrirInternal(new IntFrmClientes());
    }//GEN-LAST:event_GestorClientesActionPerformed

    private void GestorAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestorAlquileresActionPerformed
        abrirInternal(new IntFrmAlquiler());
    }//GEN-LAST:event_GestorAlquileresActionPerformed


    private void GestorVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestorVehiculosActionPerformed
        abrirInternal(new VehiculoAgregarEliminarInternal());
    }//GEN-LAST:event_GestorVehiculosActionPerformed

    private void GestorEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestorEmpleadosActionPerformed
        abrirInternal(new IntFrmEmpleados());
    }//GEN-LAST:event_GestorEmpleadosActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenú().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem GestorAlquileres;
    private javax.swing.JMenuItem GestorClientes;
    private javax.swing.JMenuItem GestorEmpleados;
    private javax.swing.JMenuItem GestorReservas;
    private javax.swing.JMenuItem GestorVehiculos;
    private javax.swing.JMenu MenuOpciones;
    // End of variables declaration//GEN-END:variables
}
